### ISSUE TITLE
Issue with styles (->css method) when load .less file loader

### ISSUE THREAD

**Issue by Vadorequest** [OpenBuildings/asset-merger#25]
Hi.

I'm running in a bug due to asset-merger here.
What I do is that I require an `application` script that require itself all the other styles.

``` javascript
->css("application.less", array('processor' => 'cssmin'))
```

If I do that, a file called `css` without any extension will be created in the cache. (folder depending on the cache_dir config). So it's loaded not as css but as **text** by the browser.

Why? I think that's because there is no `.css` extension in my filename.

If I do the same with:

``` javascript
->css("application.css.less", array('processor' => 'cssmin'))
```

It works correctly, the generated file in the cache is now called `application.css` and is correctly loaded by the browser.

But this is just a part of my issue, I just renamed my loaders and it's fine now, but I don't understand what's going on above.

This is my loader:
**assets/styles/application.css.less**

``` less
/*
* Load jQuery.
*/
@import 'jquery/jquery-ui-1.10.4.custom.min.css';
@import 'jquery/validationEngine';

/*
* Load Bootstrap.
*/
@import 'bootstrap/bootstrap.css';
@import 'bootstrap/bootstrap-dataTables.css';
```

And this is the generated file by `asset-merger`:

``` less
@import 'jquery/jquery-ui-1.10.4.custom.min.css';
@import 'bootstrap/bootstrap.css';
@import 'bootstrap/bootstrap-dataTables.css';
.formError {
  z-index: 990;
}
.formError .formErrorContent {
  z-index: 991;
}
.formError .formErrorArrow {
  z-index: 996;
}
.formErrorInsideDialog.formError {
  z-index: 5000;
}
.formErrorInsideDialog.formError .formErrorContent {
  z-index: 5001;
}
.formErrorInsideDialog.formError .formErrorArrow {
  z-index: 5006;
}
.inputContainer {
  position: relative;
  float: left;
}
.formError {
  position: absolute;
  top: 300px;
  left: 300px;
  display: block;
  cursor: pointer;
  z-index: 5000;
}
.ajaxSubmit {
  padding: 20px;
  background: #55ea55;
  border: 1px solid #999;
  display: none;
}
.formError .formErrorContent {
  background: -webkit-gradient(linear,left top,left bottom,from(#f10000),to(#b80000));
  background: -moz-linear-gradient(top,#f10000,#b80000);
  background: -o-linear-gradient(top,#f10000,#b80000);
  background: -ms-linear-gradient(top,#f10000,#b80000);
  position: relative;
  color: #fff;
  width: 150px;
  font-size: 11px;
  border: 2px solid #FFF;
  box-shadow: 0 0 5px 1px #9c9c9c;
  -moz-box-shadow: 0 0 5px 1px #9c9c9c;
  -webkit-box-shadow: 0 0 5px 1px #9c9c9c;
  -o-box-shadow: 0 0 5px 1px #9c9c9c;
  -ms-box-shadow: 0 0 5px 1px #9c9c9c;
  padding: 4px 10px 4px 10px;
  border-radius: 10px;
}
.greenPopup .formErrorContent {
  background: #33be40;
}
.blackPopup .formErrorContent {
  background: #393939;
  color: #FFF;
}
.formError .formErrorArrow {
  width: 15px;
  margin: -3px 0 0 13px;
  position: relative;
}
body[dir='rtl'] .formError .formErrorArrow,
body.rtl .formError .formErrorArrow {
  margin: -2px 13px 0 0;
}
.formError .formErrorArrowBottom {
  box-shadow: none;
  -moz-box-shadow: none;
  -webkit-box-shadow: none;
  margin: 0px 0 0 12px;
  top: 2px;
}
.formError .formErrorArrow div {
  border-left: 2px solid #FFF;
  border-right: 2px solid #FFF;
  box-shadow: 0 1px 3px #9c9c9c;
  -moz-box-shadow: 0 1px 3px #9c9c9c;
  -webkit-box-shadow: 0 1px 3px #9c9c9c;
  -o-box-shadow: 0 1px 3px #9c9c9c;
  -ms-box-shadow: 0 1px 3px #9c9c9c;
  height: 1px;
  background: #b80000;
  margin: 0 auto;
}
.formError .formErrorArrowBottom div {
  box-shadow: none;
  -moz-box-shadow: none;
  -webkit-box-shadow: none;
}
.greenPopup .formErrorArrow div {
  background: #33be40;
}
.blackPopup .formErrorArrow div {
  background: #393939;
  color: #FFF;
}
.formError .formErrorArrow .line10 {
  width: 15px;
  border: none;
}
.formError .formErrorArrow .line9 {
  width: 13px;
  border: none;
}
.formError .formErrorArrow .line8 {
  width: 11px;
}
.formError .formErrorArrow .line7 {
  width: 9px;
}
.formError .formErrorArrow .line6 {
  width: 7px;
}
.formError .formErrorArrow .line5 {
  width: 5px;
}
.formError .formErrorArrow .line4 {
  width: 3px;
}
.formError .formErrorArrow .line3 {
  width: 1px;
  border-left: 2px solid #FFF;
  border-right: 2px solid #FFF;
  border-bottom: 0 solid #FFF;
}
.formError .formErrorArrow .line2 {
  width: 3px;
  border: none;
  background: #FFF;
}
.formError .formErrorArrow .line1 {
  width: 1px;
  border: none;
  background: #FFF;
}
```

So, what's happening here? Only one file is correctly injected in the generated file using the `@import` statement, other imports are ignored.

So, what I get in the browser is a 302 error instead of the scripts, because it tries to load files using the path, but the path is wrong.

What should be done is that all `@import` files should be injected in the generated and cached `application.css` file instead to keep the imports statements.

I hope I explained well enough the problem, for now I won't use any loader. But I'm afraid to run in other issues if this is not fixed.

And I don't know why it does this, because I used libraries that use the same kind of import file and it worked. So I'm thinking that maybe an error occurs while the generated file is created that abort the operation or something like that.
